services:
  rstudio:
    image: huazhou/ucla-biostat-203b-2024w
    ports:
      - "8787:8787"
      - "8888:8888"
    environment:
      PASSWORD: 203b
      ROOT: true
      DISABLE_AUTH: true
      # USERID: 1000 # uid of rstudio user in the container
      # GROUPID: 1001 # gid of staff group in the container
    volumes:
      - "/Users/zhangli/203b-lecture:/home/rstudio/203b-lecture"
      - "/Users/zhangli/Desktop/203B/mimic-iv-2.2:/home/rstudio/mimic"
      - "/Users/zhangli/203b_hw_new:/home/rstudio/203b-hw"
      - "/Users/zhangli/212A:/home/rstudio/212a-lecture"
      - "/Users/zhangli/.ssh:/home/rstudio/.ssh"
      - "/Users/zhangli/.gitconfig:/etc/gitconfig"